# Generated by Django 4.2.7 on 2023-11-13 18:31

import czarny_kot.imgur_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('right_ban', 'right-ban'), ('top_banner', 'top-ban'), ('inter_banner', 'inter-ban'), ('bottom_banner', 'bottom-ban')], max_length=15)),
                ('script', models.TextField(blank=True, null=True)),
                ('image_banner', models.ImageField(blank=True, help_text='format .png, .jpg lub .gif', null=True, storage=czarny_kot.imgur_storage.ImgurStorage(ACCESS_TOKEN='c05f771b738040b8658fe19946379d22dd15d12b', CLIENT_ID='fd76e25e2334881', CLIENT_SECRET='eef7ee4855a3c7481ccecd3a101b9633d723c60e', CLIENT_USERNAME='CzornyKot', REFRESH_TOKEN='4fba0b83d1365ddb0407fed46c9e6c1144809c40', base_api_url='https://api.imgur.com/3/', location=''), upload_to='CzornyKotPL', verbose_name='Obraz')),
                ('link', models.URLField(blank=True, max_length=254, null=True, verbose_name='Link')),
                ('order', models.IntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
