# Generated by Django 4.2.7 on 2023-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(choices=[('inter_banner', 'inter-ban'), ('top_banner', 'top-ban'), ('bottom_banner', 'bottom-ban'), ('right_banner', 'right-ban')], max_length=15),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
