# Generated by Django 4.2.7 on 2023-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_banner_name_alter_banner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(choices=[('top_banner', 'top-ban'), ('inter_banner', 'inter-ban'), ('bottom_banner', 'bottom-ban'), ('right_banner', 'right-ban'), ('sms_banner', 'sms-ban')], max_length=15, verbose_name='Typ baneru'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.IntegerField(default=1, help_text='0 - nie pokaże baneru, 1 - dla top, bottom , sms pokaże baner', verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='Skrypt/HTML'),
        ),
    ]
