# Generated by Django 4.2.6 on 2023-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='carousel_title',
            field=models.CharField(max_length=45, verbose_name='Tytuł do karuzeli i kropki'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feat_title',
            field=models.CharField(max_length=65, verbose_name='Tytuł do fit-a'),
        ),
    ]
