# Generated by Django 4.2.6 on 2023-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_grey_fit_title_alter_post_carousel_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_feat_dot',
        ),
        migrations.AddField(
            model_name='post',
            name='photo_carousel_vertical',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Pionowe zdjęcie do karuzeli'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_dot',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Zdjęcie do kropki'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_feat',
            field=models.ImageField(default='img/kuszulkiKo_Kwadrat.webp', upload_to='img/', verbose_name='Zdjęcie do fita'),
        ),
    ]
