# Generated by Django 4.2.6 on 2023-10-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_photo_feat_dot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='sections/', verbose_name='Zdjęcie/ikona sekcji'),
        ),
    ]
