# Generated by Django 4.2.6 on 2023-11-01 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_carousel_vertical',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo_dot',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_carousel',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Wąskie zdjęcie do karuzeli (proporcja 1,78; 1973x1110)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_feat',
            field=models.ImageField(default='img/kuszulkiKo_Kwadrat.webp', upload_to='img/', verbose_name='Zdjęcie do fita (kwadrat)'),
        ),

    ]
