# Generated by Django 4.2.6 on 2023-11-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_feat',
            field=models.ImageField(upload_to='img/', verbose_name='Zdjęcie do fita (kwadrat)'),
        ),
    ]
