# Generated by Django 4.2.6 on 2023-11-05 12:13

import czarny_kot.imgur_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_photo_feat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_carousel_imgur',
            field=models.ImageField(blank=True, null=True, storage=czarny_kot.imgur_storage.ImgurStorage(), upload_to='CzornyKotPL', verbose_name='Wąskie zdjęcie do karuzeli (proporcja 1,78; 1973x1110)'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_feat_imgur',
            field=models.ImageField(blank=True, null=True, storage=czarny_kot.imgur_storage.ImgurStorage(), upload_to='CzornyKotPL', verbose_name='Zdjęcie do fita (kwadrat)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_feat',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Zdjęcie do fita (kwadrat)'),
        ),
    ]
