# Generated by Django 4.2.6 on 2023-11-05 12:25

import czarny_kot.imgur_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_lead_carousel_dot_post_photo_feat_imgur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_feat_imgur',
            field=models.ImageField(blank=True, null=True, storage=czarny_kot.imgur_storage.ImgurStorage(), upload_to='CzornyKotPL', verbose_name='Zdjęcie fita i kropki (proporcja: kwadrat)'),
        ),
    ]
