# Generated by Django 4.2.6 on 2023-11-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_photo_feat_imgur'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead_carousel_dot',
            field=models.CharField(default=' ', max_length=100, verbose_name='Lead karuzeli i kropki'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='lead_feat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead fit-a'),
        ),
    ]
