# Generated by Django 4.2.7 on 2023-11-13 18:31

import czarny_kot.imgur_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_lead_carousel_dot_alter_post_lead_feat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grey_fit_title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Szara część tytułu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_carousel',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Niskie do karuzeli (proporcja 1,78; 1973x1110)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_carousel_imgur',
            field=models.ImageField(blank=True, help_text='Proporcja: 1973x1110', null=True, storage=czarny_kot.imgur_storage.ImgurStorage(ACCESS_TOKEN='c05f771b738040b8658fe19946379d22dd15d12b', CLIENT_ID='fd76e25e2334881', CLIENT_SECRET='eef7ee4855a3c7481ccecd3a101b9633d723c60e', CLIENT_USERNAME='CzornyKot', REFRESH_TOKEN='4fba0b83d1365ddb0407fed46c9e6c1144809c40', base_api_url='https://api.imgur.com/3/', location=''), upload_to='CzornyKotPL', verbose_name='Niskie do karuzeli'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo_feat_imgur',
            field=models.ImageField(blank=True, help_text='Proporcja: kwadrat', null=True, storage=czarny_kot.imgur_storage.ImgurStorage(ACCESS_TOKEN='c05f771b738040b8658fe19946379d22dd15d12b', CLIENT_ID='fd76e25e2334881', CLIENT_SECRET='eef7ee4855a3c7481ccecd3a101b9633d723c60e', CLIENT_USERNAME='CzornyKot', REFRESH_TOKEN='4fba0b83d1365ddb0407fed46c9e6c1144809c40', base_api_url='https://api.imgur.com/3/', location=''), upload_to='CzornyKotPL', verbose_name='Do fita i kropki'),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.FileField(blank=True, null=True, storage=czarny_kot.imgur_storage.ImgurStorage(ACCESS_TOKEN='c05f771b738040b8658fe19946379d22dd15d12b', CLIENT_ID='fd76e25e2334881', CLIENT_SECRET='eef7ee4855a3c7481ccecd3a101b9633d723c60e', CLIENT_USERNAME='CzornyKot', REFRESH_TOKEN='4fba0b83d1365ddb0407fed46c9e6c1144809c40', base_api_url='https://api.imgur.com/3/', location=''), upload_to='CzornyKotPL', verbose_name='Zdjęcie/ikona sekcji'),
        ),
    ]
