# Generated by Django 4.2.7 on 2023-11-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_grey_fit_title_alter_post_photo_carousel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejność'),
        ),
    ]
