CZORNY_KOT_CATALOG = {
        ('0', 'anarchizm'),
        ('00', 'anarchizm klasyczny'),
        ('000', 'mutualizm'),
        ('001', 'anarchizm społeczny'),
        ('001.0', 'anarchizm kolektywistyczny'),
        ('001.1', 'anarchizm komunistyczny'),
        ('001.2', 'anarchizm syndykalistyczny'),
        ('002', ' anarchizm indywidualistyczny'),
        ('002.0', 'anarchizm filozoficzny'),
        ('002.1', 'anarchizm egoistyczny'),
        ('002.2', 'anarchizm egzystencjalny'),
        ('002.3', 'illegalizm'),
        ('01', 'anarchizm postklasyczny'),
        ('010', 'anarchizm feministyczny'),
        ('011', 'anarchizm pacyfistyczny'),
        ('012', 'anarchizm religijny'),
        ('012.0', 'chrześcijański anarchizm'),
        ('013', 'anarchizm bezprzymiotnikowy'),
        ('013.0', 'anarchizm syntezy'),
        ('014', 'platformizm'),
        ('015', 'zielony anarchizm'),
        ('015.0', 'anarchoprymitywizm'),
        ('015.1', 'anarchonaturyzm'),
        ('015.2', 'ekologia społeczna'),
        ('015.3', 'anarchizm wegański'),
        ('02', 'anarchizm współczesny'),
        ('020', 'insurekcjonizm'),
        ('021', 'anarchotranshumanizm'),
        ('022', 'postanarchizm'),
        ('023', 'anarchizm postlewicowy'),
        ('024', 'anarchizm queerowy'),
        ('025', 'libertarianizm'),
        ('026', 'kooperatywizm'),
        ('1', 'myśl i nauki społeczne, prawo'),
        ('10', 'ruchy wolnościowe'),
        ('100', 'antyfaszyzm'),
        ('101', 'antykomunizm'),
        ('102', 'pacyfizm'),
        ('103', 'antymilitaryzm'),
        ('11', 'feminizm'),
        ('12', 'politologia'),
        ('120', 'media a demokracja'),
        ('13', 'prawa człowieka'),
        ('130', 'prawa obywatelskie'),
        ('131', 'terror instytucji publicznych'),
        ('132', 'terror korporacji'),
        ('133', 'terror policji'),
        ('134', 'terror państwa'),
        ('135', 'prawa mniejszości'),
        ('14', 'ekologia'),
        ('140', 'prawa zwierząt'),
        ('141', 'wegetarianizm, weganizm'),
        ('142', 'ekologia głęboka'),
        ('143', 'zmiany klimatu'),
        ('2', 'Kultura alternatywna'),
        ('20', 'muzyka'),
        ('200', 'scena alternatywna'),
        ('201', "trzeci obieg"),
        ('21', 'teatr'),
        ('22', 'sztuka'),
        ('220', 'sztuka uliczna'),
        ('220.0', 'graffiti'),
        ('220.1', 'murale'),
}

ITEM_TYPE = {
    ('(00)', 'album, książka artystyczna'),
    ('(01)', 'artykuł'),
    ('(02)', 'czasopismo'),
    ('(03)', 'druk ulotny'),
    ('(04)', 'film (dokument, fabuła)'),
    ('(05)', 'grafika, fotografia, rysunek'),
    ('(06)', 'komiks, książka obrazkowa'),
    ('(07)', 'książka'),
    ('(08)', 'mapa'),
    ('(09)', 'muzyka'),
    ('(10)', 'nagranie audio'),
    ('(11)', 'nagranie wideo'),
}

BOOK_FORM = {
    ('(070)', 'miękka oprawa'),
    ('(071)', 'twarda oprawa'),
    ('(072)', 'audiobook'),
    ('(073)', 'e-book'),
}

COMMON_FORMS = {
    ('{0}', 'tradycyjna'),
    ('{1}', 'elektroniczna'),
}

CARRIER = {
    ('|1', 'CD, DVD, blu-ray'),
    ('|2', 'kaseta magnetofonowa, VHS lub inna'),
    ('|3', 'pendrive, karta flash lub SD'),
    ('|4', 'dysk zewnętrzny'),

}

GENRE = {
    ('-0', 'dramat'),
    ('-1', "dzieło niesamoistne, opublikowane w czasopiśmie lub pracy zbiorowej."),
    ('-2', 'literatura faktu, esej, felieton, publicystyka'),
    ('-3', 'poezja'),
    ('-4', 'poradnik, przewodnik'),
    ('-5', 'powieść, opowiadanie, nowela'),
    ('-6', 'publikacja dydaktyczna'),
    ('-7', 'publikacja fachowa'),
    ('-8', 'publikacja informacyjna'),
    ('-9', 'publikacja naukowa'),
    ('-10', 'publikacja popularnonaukowa'),
    ('-11', 'publikacja promocyjna'),
    ('-12', 'publikacja urzędowa i akt prawny'),
}

LANGUAGE = {
    ('=0', 'polski'),
    ('=1', 'angielski'),
    ('=2', 'francuski'),
    ('=3', 'hiszpański'),
    ('=4', 'niemiecki'),
    ('=5', 'rosyjski'),
}

LOCATION = {

}

FILE_FORMATS = {
    ('[0]', 'xwm'),
    ('[1]', 'CD-Audio'),
    ('[2]', 'WAV'),
    ('[3]', 'AIF, AIFF, AIFC, AIFR'),
    ('[4]', 'FLAC'),
    ('[5]', 'WavPack (wv),'),
    ('[6]', 'Monkey’s Audio (ape, apl)'),
    ('[7]', 'True Audio (TTA)'),
    ('[8]', 'OptimFROG'),
    ('[9]', 'TAK'),
    ('[10]', 'Shorten (shn)'),
    ('[11]', 'Meridian Lossless Packing (MLP)'),
    ('[12]', 'DTS-HD Master Audio'),
    ('[13]', 'MP2, MPG, MPE, MPEG, MPEG2'),
    ('[14]', 'Musepack (MPC)'),
    ('[15]', 'MP3'),
    ('[16]', 'Mp3Pro'),
    ('[17]', 'M4A (MPEG-4 Audio Layer),'),
    ('[18]', 'Ogg Vorbis (Ogg, Oga),'),
    ('[19]', 'Opus'),
    ('[20]', 'QuickTime Audio'),
    ('[21]', 'RealAudio'),
    ('[22]', 'WMA (Windows Media Audio)'),
    ('[23]', 'ATRAC'),
    ('[24]', 'Beatnik'),
    ('[25]', 'Liquid Audio'),
    ('[26]', 'a2bmusic'),
    ('[27]', 'Master Quality Authenticated (MQA)'),
    ('[28]', '3GP'),
    ('[29]', 'ASF'),
    ('[30]', 'AVI'),
    ('[31]', 'DV'),
    ('[32]', 'DVD'),
    ('[33]', 'FLV'),
    ('[34]', 'M2TS'),
    ('[35]', 'MKV'),
    ('[36]', 'MOV'),
    ('[37]', 'MP4'),
    ('[38]', 'MPG'),
    ('[39]', 'Ogg'),
    ('[40]', 'SMV'),
    ('[41]', 'SVCD'),
    ('[42]', 'TS'),
    ('[43]', 'WMV'),
    ('[44]', 'VCD'),
    ('[45]', 'TXT'),
    ('[46]', 'RTF'),
    ('[47]', 'DOC/DOCX'),
    ('[48]', 'ODT'),
    ('[49]', 'CSS'),
    ('[50]', 'HTML'),
    ('[51]', 'HTM'),
    ('[52]', 'XML'),
    ('[53]', 'WPS'),
    ('[54]', 'CBR, CBZ, CB7, CBT, CBA'),
    ('[55]', 'DJVU'),
    ('[56]', 'EPUB'),
    ('[57]', 'FB2'),
    ('[58]', 'IBOOK'),
    ('[59]', 'INF'),
    ('[60]', 'AZW, AZW3, KFX'),
    ('[61]', 'LIT'),
    ('[62]', 'PRC, MOBI'),
    ('[63]', 'EXE'),
    ('[64]', 'PKG'),
    ('[65]', 'PDB'),
    ('[67]', 'PDF'),
    ('[68]', 'PS'),
    ('[69]', 'TR2, TR3'),
    ('[70]', 'OXPS, XPS'),
}

MAGAZINE_CYCLE = {
    ('{1}', 'dziennik',),
    ('{2}', 'tygodnik',),
    ('{3}', '2-tygodnik',),
    ('{4}', 'miesięcznik',),
    ('{5}', 'kwartalnik',),
    ('{6}', 'inny')
}
