# Generated by Django 4.2.7 on 2023-11-27 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=20)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, choices=[('book', 'książka'), ('magazine', 'czasopismo'), ('map', 'mapa'), ('audio_record', 'nagranie audio'), ('article', 'artykuł'), ('video', 'film'), ('empheral_item', 'druk ulotny')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('translator', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('series_number', models.CharField(blank=True, max_length=5)),
                ('edition', models.CharField(blank=True, max_length=4, null=True)),
                ('first_publication_year', models.DateField(blank=True, null=True)),
                ('publication_year', models.DateField(blank=True, null=True)),
                ('kind', models.CharField(choices=[('e-book', 'e-book'), ('softcover', 'miękka oprawa'), ('hardcover', 'twarda oprawa'), ('audiobook', 'audiobook')], max_length=15, verbose_name='rodzaj')),
                ('language', models.CharField(max_length=20)),
                ('page_number', models.IntegerField()),
                ('carrier', models.CharField(blank=True, max_length=20)),
                ('file_format', models.CharField(blank=True, max_length=20)),
                ('playback_time', models.CharField(blank=True, max_length=10)),
                ('ISBN', models.CharField(blank=True, max_length=15)),
                ('ISSN', models.CharField(blank=True, max_length=15)),
                ('authors', models.ManyToManyField(blank=True, to='catalog.author')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.publisher', verbose_name='Wydawnictwo')),
            ],
        ),
    ]
